/**
 * Security event service — single owner for security telemetry
 * generated by the knowledge ingestion pipeline (P2).
 *
 * Events flow into the existing audit log (no second audit table per
 * plan rule 3.13). The Command Center consumes them via the audit
 * module's read API.
 *
 * The service also emits an in-process `EventEmitter` notification so
 * the Command Center P8 module can refresh inventory without a tight
 * database polling loop.
 */
import { Injectable, Logger } from '@nestjs/common';
import { EventEmitter } from 'node:events';
import { AuditService } from '../../audit/audit.service';

export type KnowledgeSecurityEventKind =
  | 'MALWARE_DETECTED'
  | 'DLP_VIOLATION'
  | 'ARCHIVE_BOMB'
  | 'INJECTION_SUSPECTED'
  | 'ACL_VIOLATION'
  | 'ENCRYPTION_FAILURE';

export interface KnowledgeSecurityEvent {
  tenantId: string;
  actorId?: string;
  kind: KnowledgeSecurityEventKind;
  resource: string;
  resourceId?: string;
  details: Record<string, unknown>;
  /** When `true` the event is a hard failure (ingestion rejected). */
  fatal: boolean;
}

@Injectable()
export class KnowledgeSecurityEventService {
  private readonly logger = new Logger(KnowledgeSecurityEventService.name);
  private readonly emitter = new EventEmitter();

  constructor(private readonly audit: AuditService) {}

  /** Subscribe for Command Center inventory; returns an unsubscribe fn. */
  subscribe(handler: (e: KnowledgeSecurityEvent) => void): () => void {
    this.emitter.on('event', handler);
    return () => this.emitter.off('event', handler);
  }

  async emit(event: KnowledgeSecurityEvent): Promise<void> {
    this.logger.warn(
      `[security] tenant=${event.tenantId} kind=${event.kind} fatal=${event.fatal} resource=${event.resource}/${event.resourceId ?? '-'}`,
    );
    await this.audit.log({
      actor: event.actorId ?? 'system',
      action: `knowledge.security.${event.kind.toLowerCase()}`,
      resource: event.resource,
      resourceId: event.resourceId,
      tenantId: event.tenantId,
      result: event.fatal ? 'failure' : 'success',
      details: { ...event.details, fatal: event.fatal },
    });
    this.emitter.emit('event', event);
  }
}
