import type { AuthorizationContext } from '../contracts';
import {
  PHASE8_VERSION,
  type Phase8RunnerReport,
  type WorkloadMetricBundle,
  type WorkloadProfile,
  type WorkloadCaseResult,
  type Phase8Counters,
  type SloPolicy,
  type SloEvaluation,
  type AdapterRegistration,
  type Phase8ProductionAdapter,
} from './contracts';
import {
  Phase8Coordinator,
  buildWorkloadRunner,
  WorkloadRunner,
  computePhase8Counters,
  finalizePhase8Report,
  checksumPhase8Report,
  PHASE8_KIND_LABELS,
  defaultProfiles,
  evaluateSloPolicy,
  isSloPolicyEnforceable,
  evaluateCapacityGate,
  runWithGuards,
  RunnerCancelledError,
  RunnerTimeoutError,
  type Phase8CoordinatorInput,
  type Phase8RunOptions,
} from './runners';
import {
  InMemoryMetricsPort,
  InMemoryPressurePort,
  InMemoryCachePort,
  InMemoryDbPort,
  InMemoryQueuePort,
  InMemoryProviderPort,
  InMemoryCleanupPort,
  FailingCleanupAdapter,
  UnsupportedCleanupAdapter,
  Phase8EvidenceSink,
  DeterministicCorrectnessOracle,
  DeterministicIsolationOracle,
  TenantKeyIsolationOracle,
  SimulatedWorkloadPort,
  createAuthorizationContext,
  buildLatencyDistribution,
  buildConfidenceIntervals,
  buildTokenCost,
  defaultSaturation,
  detectSaturationFromCurves,
  defaultRecovery,
  determineRegression,
  expectedCostPerToken,
  emptyTokenCost,
  WORKLOAD_KINDS,
  InMemoryPhase8AdapterRegistry,
  UnsupportedPhase8Adapters,
  listAdapters,
  unsupportedRegistrationStamps,
  UNSUPPORTED_ADAPTER_REASON,
  InMemoryOperationalAlertPort,
  UnsupportedOperationalAlertPort,
  UNSUPPORTED_ALERT_REASON,
  UnsupportedProductionAdapterStub,
  PRODUCTION_ADAPTER_UNSUPPORTED_PREFIX,
  unsupportedProductionAdapterStubs,
  SUFFICIENT_SAMPLE_THRESHOLD,
  buildStatisticalConfidence,
  type Phase8AdapterRegistry,
  type OperationalAlertPort as _OperationalAlertPort,
  type ProductionAdapterStubBase as _ProductionAdapterStubBase,
  type ReportSchemaVersion as _ReportSchemaVersion,
  type ReportSchemaMigration as _ReportSchemaMigration,
  type ReportSchemaMigrator as _ReportSchemaMigrator,
} from './ports';

export * from './contracts';
export * from './ports';
export * from './runners';
export * from './report-writer';
export * from './ci-lane';
export * from './report-migration';
export * from './alerts';

export {
  Phase8Coordinator,
  buildWorkloadRunner,
  WorkloadRunner,
  computePhase8Counters,
  finalizePhase8Report,
  checksumPhase8Report,
  PHASE8_KIND_LABELS,
  defaultProfiles,
  evaluateSloPolicy,
  isSloPolicyEnforceable,
  evaluateCapacityGate,
  runWithGuards,
  RunnerCancelledError,
  RunnerTimeoutError,
  InMemoryMetricsPort,
  InMemoryPressurePort,
  InMemoryCachePort,
  InMemoryDbPort,
  InMemoryQueuePort,
  InMemoryProviderPort,
  InMemoryCleanupPort,
  FailingCleanupAdapter,
  UnsupportedCleanupAdapter,
  Phase8EvidenceSink,
  DeterministicCorrectnessOracle,
  DeterministicIsolationOracle,
  TenantKeyIsolationOracle,
  SimulatedWorkloadPort,
  createAuthorizationContext,
  buildLatencyDistribution,
  buildConfidenceIntervals,
  buildStatisticalConfidence,
  buildTokenCost,
  defaultSaturation,
  detectSaturationFromCurves,
  defaultRecovery,
  determineRegression,
  expectedCostPerToken,
  emptyTokenCost,
  WORKLOAD_KINDS,
  InMemoryPhase8AdapterRegistry,
  UnsupportedPhase8Adapters,
  listAdapters,
  unsupportedRegistrationStamps,
  UNSUPPORTED_ADAPTER_REASON,
  InMemoryOperationalAlertPort,
  UnsupportedOperationalAlertPort,
  UNSUPPORTED_ALERT_REASON,
  UnsupportedProductionAdapterStub,
  PRODUCTION_ADAPTER_UNSUPPORTED_PREFIX,
  unsupportedProductionAdapterStubs,
  SUFFICIENT_SAMPLE_THRESHOLD,
  PHASE8_VERSION,
};

export type {
  AuthorizationContext,
  Phase8RunnerReport,
  WorkloadMetricBundle,
  WorkloadProfile,
  WorkloadCaseResult,
  Phase8Counters,
  SloPolicy,
  SloEvaluation,
  AdapterRegistration,
  Phase8ProductionAdapter,
  Phase8CoordinatorInput,
  Phase8RunOptions,
  Phase8AdapterRegistry,
};
